version: '3'
services:
  django_app:
    image: vercel_api:latest
    container_name: vercel_api
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
    volumes:
      - .:/app